version: "3.9"
services:
  mysql-ventury:
    networks:
        dev_docker:
            ipv4_address: 177.177.195.55
    image: mariadb:10.4
    container_name: mysql-ventury
    working_dir: /application
    volumes:
        - .:/application
        - ./docker/mysql/storage/db-support:/var/lib/mysql
        - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        - ./docker/mysql/init:/docker-entrypoint-initdb.d
    tty: true
    environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_USER=root
        - MYSQL_PASSWORD=
        - TERM=xterm-256color
    ports:
        - '3306'

  webserver:
    networks:
      dev_docker:
        aliases:
          - ventury.local
        ipv4_address: 177.177.195.4
    image: nginx:alpine
    container_name: ventury-webserver
    working_dir: /application
    tty: true
    environment:
      - TERM=xterm-256color
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/ssl
    ports:
      - 80
      - 443
    depends_on:
      - php-fpm

  php-fpm:
    networks:
      dev_docker:
        ipv4_address: 177.177.195.5
#    image: ${PHP_FPM_IMAGE}
    build: 'docker/php-fpm'
    container_name: ventury-php-fpm
    tty: true
    environment:
      - TERM=xterm-256color
      - XDEBUG_CONFIG=remote_host=172.17.0.1
      - COMPOSER_MEMORY_LIMIT=-1
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini

#  queue:
#    networks:
#      dev_docker:
#        ipv4_address: 177.177.195.7
#    image: ${PHP_FPM_IMAGE}
#    container_name: ventury-queue
#    tty: true
#    environment:
#      - CONTAINER_ROLE=queue
#    working_dir: /application
#    volumes:
#      - .:/application
#      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
#      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
#    restart: unless-stopped
#    depends_on:
#      - redis

networks:
  dev_docker:
    name: ventury_dev_docker
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "177.177.195.0/16"
